package Exception_prac;

import java.io.IOException;

public class Exception_prac {
	
	public void m1() throws IOException{
		
		System.out.println("m1 method inside the Exception class");
	}

	public void m2() {
		
		System.out.println("Test");
	}
}
